# Generated by Django 4.2.11 on 2026-03-20 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia', models.CharField(choices=[('COM', 'Compuestas'), ('CRU', 'Cruciferas (Brásicas)'), ('UMB', 'Cruciferas'), ('SOL', 'Solanaceas'), ('GRA', 'Gramineas'), ('LEG', 'Leguminosas'), ('QUE', 'Quenopoidaceas'), ('ALL', 'Alliaceas'), ('CUC', 'Cucurbitaceas'), ('CON', 'Convolvulaceas'), ('ASP', 'Asparagaceae'), ('API', 'Apiaceae')], max_length=3)),
                ('nombre_cientifico', models.CharField(blank=True, max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_siembra', models.CharField(choices=[('D', 'Directa'), ('S', 'Semillero'), ('T', 'Directa / Semillero')], max_length=1)),
                ('luna_siembra', models.CharField(blank=True, choices=[('C', 'Cuarto Creciente'), ('M', 'Cuarto Menguante'), ('L', 'Llena'), ('N', 'Nueva')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('tratamiento', models.CharField(blank=True, max_length=255)),
                ('agente_causal', models.CharField(choices=[('HON', 'Hongos'), ('BAC', 'Bacterias'), ('NEM', 'Nematodos'), ('VIR', 'Virus'), ('PAR', 'Plantas Parasitas')], max_length=3)),
                ('sintomas', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fecha_Siembra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.CharField(choices=[('1', 'Primer Semana'), ('2', 'Segunda Semana'), ('3', 'Tercer Semana'), ('4', 'Cuarta Semana')], max_length=1, null=True)),
                ('mes', models.CharField(choices=[('ENE', 'Enero'), ('FEB', 'Febrero'), ('MAR', 'Marzo'), ('ABR', 'Abril'), ('MAY', 'Mayo'), ('JUN', 'Junio'), ('JUL', 'Julio'), ('AGO', 'Agosto'), ('SEP', 'Septiembre'), ('OCT', 'Octubre'), ('NOV', 'Noviembre'), ('DIC', 'Diciembre')], max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Plagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('tratamiento', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Riego_Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_corta', models.CharField(blank=True, max_length=30)),
                ('cantidad', models.SmallIntegerField()),
                ('frecuencia', models.SmallIntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Suelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_corta', models.CharField(blank=True, max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Variedades_Cultivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cultivos')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variedades', to='configuracion.cultivos')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tiempos_Variedades_Cultivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.CharField(choices=[('O', 'Optimo'), ('N', 'Normal'), ('M', 'Como maximo')], max_length=1)),
                ('dia_desde', models.SmallIntegerField(blank=0)),
                ('dia_hasta', models.SmallIntegerField(blank=0)),
                ('observacion', models.CharField(blank=True, max_length=50)),
                ('variedad_cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.variedades_cultivos')),
            ],
        ),
        migrations.CreateModel(
            name='Temperaturas_Variedades_Cultivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_corta', models.CharField(blank=True, max_length=30)),
                ('valor_minimo', models.IntegerField(blank=True, null=True)),
                ('valor_maximo', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('variedad_cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperatura', to='configuracion.variedades_cultivos')),
            ],
        ),
        migrations.CreateModel(
            name='Suelos_Cultivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.cultivos')),
                ('suelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.suelos')),
            ],
        ),
        migrations.CreateModel(
            name='Plagas_Cultivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.cultivos')),
                ('plagas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.plagas')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=255)),
                ('web', models.URLField(blank=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mes_Siembra_Variedades_Cultivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_siembra_desde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fecha_siembra_desde', to='configuracion.fecha_siembra')),
                ('fecha_siembra_hasta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fecha_siembra_hasta', to='configuracion.fecha_siembra')),
                ('variedad_cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_siembra', to='configuracion.variedades_cultivos')),
            ],
        ),
        migrations.CreateModel(
            name='Luz_Variedades_Cultivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_corta', models.CharField(blank=True, max_length=30)),
                ('valor_minimo', models.IntegerField(blank=True, null=True)),
                ('valor_maximo', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('variedad_cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luz', to='configuracion.variedades_cultivos')),
            ],
        ),
        migrations.CreateModel(
            name='Hortelano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apodo', models.CharField(blank=True, max_length=30)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GaleriaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('imagen', models.ImageField(blank=True, upload_to='galeriaPrincipal')),
                ('leyenda', models.CharField(blank=True, max_length=255)),
                ('galeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.galeria')),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedades_Cultivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.cultivos')),
                ('enfermedades', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.enfermedades')),
            ],
        ),
        migrations.CreateModel(
            name='Asociaciones_Cultivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiosa', models.BooleanField(blank=True, max_length=255)),
                ('asociacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_asociacion', to='configuracion.cultivos')),
                ('cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.cultivos')),
            ],
        ),
    ]
