# Generated by Django 4.2.11 on 2026-03-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variedades_cultivos',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
