# Generated by Django 4.2.11 on 2026-03-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fecha_siembra',
            name='semana',
        ),
        migrations.AddField(
            model_name='fecha_siembra_variedades_cultivos',
            name='desc_corta',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
