# Generated by Django 4.2.11 on 2026-03-20 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_variedades_cultivos_descripcion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mes_Siembra_Variedades_Cultivos',
            new_name='Fecha_Siembra_Variedades_Cultivos',
        ),
    ]
