# Generated by Django 4.2.11 on 2026-03-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_remove_fecha_siembra_semana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fecha_siembra',
            name='semana',
            field=models.CharField(choices=[('1', 'Primer Semana'), ('2', 'Segunda Semana'), ('3', 'Tercer Semana'), ('4', 'Cuarta Semana')], max_length=1, null=True),
        ),
    ]
