# Generated by Django 3.2.13 on 2022-06-16 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_rename_hotelano_huerta_hortelano'),
    ]

    operations = [
        migrations.AddField(
            model_name='hortelano',
            name='mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='huerta',
            name='ancho',
            field=models.SmallIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='huerta',
            name='coord_x',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='huerta',
            name='coord_y',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='huerta',
            name='largo',
            field=models.SmallIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Canteros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('ancho', models.SmallIntegerField()),
                ('largo', models.SmallIntegerField()),
                ('huerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.huerta')),
            ],
        ),
    ]
