# Generated by Django 4.2.11 on 2026-03-20 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_rename_mes_siembra_variedades_cultivos_fecha_siembra_variedades_cultivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecha_siembra_variedades_cultivos',
            name='variedad_cultivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fecha_siembra', to='configuracion.variedades_cultivos'),
        ),
    ]
