# Generated by Django 4.2.11 on 2026-03-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_fecha_siembra_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecha_siembra',
            name='mes',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fecha_siembra',
            name='semana',
            field=models.CharField(max_length=10),
        ),
    ]
