# Generated by Django 3.2.13 on 2022-07-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_hortelano_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteros',
            name='ubicacion_x',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='canteros',
            name='ubicacion_y',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
