# Generated by Django 3.2.13 on 2022-07-29 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0007_ingredient_instruction_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Instruction',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
