# Generated by Django 3.2.13 on 2022-08-04 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0008_auto_20220729_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('tratamiento', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Plagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('tratamiento', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TierrasCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cultivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('tipo_siembra', models.CharField(blank=True, max_length=255)),
                ('distancia', models.SmallIntegerField()),
                ('luz', models.CharField(blank=True, max_length=50)),
                ('nombre_cientifico', models.CharField(blank=True, max_length=50)),
                ('enfermedades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.enfermedades')),
                ('plagas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.plagas')),
                ('tierra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.tierrascultivo')),
            ],
        ),
    ]
