# Generated by Django 3.2.13 on 2022-08-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0009_cultivos_enfermedades_plagas_tierrascultivo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TierrasCultivo',
            new_name='Tierras_Cultivo',
        ),
    ]
