# Generated by Django 3.2.13 on 2022-08-04 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0010_rename_tierrascultivo_tierras_cultivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivos',
            name='asociacion_beneficiosa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asosiacion_beneficiosa', to='configuracion.cultivos'),
        ),
        migrations.AddField(
            model_name='cultivos',
            name='asociacion_no_beneficiosa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asosiacion_no_beneficiosa', to='configuracion.cultivos'),
        ),
    ]
