# Generated by Django 3.2.13 on 2022-08-04 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0013_auto_20220804_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Luz_Necesaria_Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.SmallIntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='cultivos',
            name='luna_siembra',
            field=models.CharField(choices=[('C', 'Cuarto Creciente'), ('M', 'Cuarto Menguante'), ('L', 'Llena'), ('N', 'Nueva')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cultivos',
            name='tipo_siembra',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cultivos',
            name='luz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.luz_necesaria_cultivo'),
        ),
    ]
