# Generated by Django 3.2.13 on 2023-03-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0021_auto_20230329_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='tierras_cultivo',
            name='desc_corta',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
