# Generated by Django 3.2.13 on 2023-03-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0026_alter_cultivos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivos',
            name='imagen',
            field=models.ImageField(upload_to='data/archivos/cultivos'),
        ),
    ]
