# Generated by Django 3.2.13 on 2023-03-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0027_alter_cultivos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivos',
            name='imagen',
            field=models.ImageField(upload_to='regihuer/archivos/cultivos'),
        ),
    ]
