# Generated by Django 3.2.13 on 2023-04-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0032_auto_20230411_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='cantero_cultivos',
            name='cantidad_sembrada',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cantero_cultivos',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cultivos',
            name='dias_germinacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
