# Generated by Django 3.2.13 on 2023-04-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0035_auto_20230417_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivos',
            name='fecha_siembra_desde',
        ),
        migrations.RemoveField(
            model_name='cultivos',
            name='fecha_siembra_hasta',
        ),
        migrations.AddField(
            model_name='cultivos',
            name='mes_siembra_desde',
            field=models.CharField(choices=[('ENE', 'Enero'), ('FEB', 'Febrero'), ('MAR', 'Marzo')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='cultivos',
            name='mes_siembra_hasta',
            field=models.CharField(choices=[('ENE', 'Enero'), ('FEB', 'Febrero'), ('MAR', 'Marzo')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='cultivos',
            name='semana_siembra_desde',
            field=models.CharField(choices=[('1', 'Primer Semana'), ('2', 'Segunda Semana'), ('3', 'Tercer Semana'), ('4', 'Cuarta Semana')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='cultivos',
            name='semana_siembra_hasta',
            field=models.CharField(choices=[('1', 'Primer Semana'), ('2', 'Segunda Semana'), ('3', 'Tercer Semana'), ('4', 'Cuarta Semana')], max_length=1, null=True),
        ),
    ]
