# Generated by Django 4.2.11 on 2025-03-28 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0037_auto_20230417_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='GaleriaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('imagen', models.ImageField(blank=True, upload_to='galeriaPrincipal')),
                ('leyenda', models.CharField(blank=True, max_length=255)),
                ('galeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.galeria')),
            ],
        ),
    ]
