# Generated by Django 4.2.11 on 2025-04-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0038_galeria_galeriaimagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hortelano',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='hortelano',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='hortelano',
            name='apodo',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
