# Generated by Django 4.2.11 on 2025-04-07 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0039_remove_hortelano_mail_remove_hortelano_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canteros',
            name='huerta',
        ),
        migrations.RemoveField(
            model_name='huerta',
            name='hortelano',
        ),
        migrations.DeleteModel(
            name='Cantero_Cultivos',
        ),
        migrations.DeleteModel(
            name='Canteros',
        ),
        migrations.DeleteModel(
            name='Huerta',
        ),
    ]
