# Generated by Django 4.2.11 on 2025-04-14 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0041_remove_cultivos_variedad_variedad_cultivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivos',
            name='asociacion_beneficiosa',
        ),
        migrations.RemoveField(
            model_name='cultivos',
            name='asociacion_no_beneficiosa',
        ),
        migrations.RemoveField(
            model_name='cultivos',
            name='enfermedades',
        ),
        migrations.RemoveField(
            model_name='cultivos',
            name='plagas',
        ),
        migrations.CreateModel(
            name='Plagas_Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.cultivos')),
                ('plagas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.plagas')),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedades_Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.cultivos')),
                ('enfermedades', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.enfermedades')),
            ],
        ),
        migrations.CreateModel(
            name='Asociacion_Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiosa', models.BooleanField(blank=True, max_length=255)),
                ('asociacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to='configuracion.cultivos')),
                ('cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.cultivos')),
            ],
        ),
    ]
