# Generated by Django 4.2.11 on 2025-04-14 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0043_alter_asociacion_cultivo_asociacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riego_Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.SmallIntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='cultivos',
            name='riego',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.riego_cultivo'),
        ),
    ]
