# Generated by Django 4.2.11 on 2025-04-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0044_riego_cultivo_cultivos_riego'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperaturas_cultivos',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='temperaturas_cultivos',
            name='valores',
        ),
        migrations.AddField(
            model_name='luz_necesaria_cultivo',
            name='desc_corta',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='ph_suelo',
            name='desc_corta',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='temperaturas_cultivos',
            name='desc_corta',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='temperaturas_cultivos',
            name='valor_maximo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperaturas_cultivos',
            name='valor_minimo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tierras_cultivo',
            name='desc_corta',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
