# Generated by Django 4.2.11 on 2025-04-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0045_remove_temperaturas_cultivos_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riego_cultivo',
            name='desc_corta',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
