# Generated by Django 4.2.11 on 2025-04-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0046_riego_cultivo_desc_corta'),
    ]

    operations = [
        migrations.AddField(
            model_name='riego_cultivo',
            name='frecuencia',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
