# Generated by Django 4.2.11 on 2026-03-13 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0047_riego_cultivo_frecuencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fecha_Siembra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.CharField(choices=[('1', 'Primer Semana'), ('2', 'Segunda Semana'), ('3', 'Tercer Semana'), ('4', 'Cuarta Semana')], max_length=1, null=True)),
                ('mes', models.CharField(choices=[('ENE', 'Enero'), ('FEB', 'Febrero'), ('MAR', 'Marzo'), ('ABR', 'Abril'), ('MAY', 'Mayo'), ('JUN', 'Junio'), ('JUL', 'Julio'), ('AGO', 'Agosto'), ('SEP', 'Septiembre'), ('OCT', 'Octubre'), ('NOV', 'Noviembre'), ('DIC', 'Diciembre')], max_length=3, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Asociacion_Cultivo',
            new_name='Asociaciones_Cultivos',
        ),
        migrations.RenameModel(
            old_name='Enfermedades_Cultivo',
            new_name='Enfermedades_Cultivos',
        ),
        migrations.RenameModel(
            old_name='Plagas_Cultivo',
            new_name='Plagas_Cultivos',
        ),
        migrations.RemoveField(
            model_name='cultivos',
            name='mes_siembra_desde',
        ),
        migrations.RemoveField(
            model_name='cultivos',
            name='mes_siembra_hasta',
        ),
        migrations.RemoveField(
            model_name='cultivos',
            name='semana_siembra_desde',
        ),
        migrations.RemoveField(
            model_name='cultivos',
            name='semana_siembra_hasta',
        ),
        migrations.RemoveField(
            model_name='cultivos',
            name='tierra',
        ),
        migrations.RenameModel(
            old_name='Tierras_Cultivo',
            new_name='Suelos',
        ),
        migrations.RenameModel(
            old_name='Variedad_Cultivo',
            new_name='Variedades_Cultivos',
        ),
        migrations.CreateModel(
            name='Tiempos_Variedades_Cultivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.CharField(choices=[('O', 'Optimo'), ('N', 'Normal'), ('M', 'Como maximo')], max_length=1)),
                ('dia_desde', models.SmallIntegerField(blank=0)),
                ('dia_hasta', models.SmallIntegerField(blank=0)),
                ('observacion', models.CharField(blank=True, max_length=50)),
                ('variedad_cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.variedades_cultivos')),
            ],
        ),
        migrations.CreateModel(
            name='Suelos_Cultivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.cultivos')),
                ('suelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.suelos')),
            ],
        ),
        migrations.CreateModel(
            name='Mes_Siembra_Variedades_Cultivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_siembra_desde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fecha_siembra_desde', to='configuracion.fecha_siembra')),
                ('fecha_siembra_hasta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fecha_siembra_hasta', to='configuracion.fecha_siembra')),
                ('variedad_cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.variedades_cultivos')),
            ],
        ),
    ]
