# Generated by Django 4.2.11 on 2026-03-13 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0048_fecha_siembra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivos',
            name='dias_germinacion',
        ),
        migrations.RemoveField(
            model_name='cultivos',
            name='luz',
        ),
        migrations.RemoveField(
            model_name='cultivos',
            name='riego',
        ),
        migrations.RemoveField(
            model_name='cultivos',
            name='temperaturas',
        ),
        migrations.AddField(
            model_name='variedades_cultivos',
            name='luz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.luz_necesaria_cultivo'),
        ),
    ]
