# Generated by Django 4.2.11 on 2026-03-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0049_remove_cultivos_dias_germinacion_remove_cultivos_luz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivos',
            name='imagen',
        ),
        migrations.AddField(
            model_name='variedades_cultivos',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='cultivos'),
        ),
    ]
