# Generated by Django 4.2.11 on 2026-03-13 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0050_remove_cultivos_imagen_variedades_cultivos_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivos',
            name='distancia',
        ),
        migrations.RemoveField(
            model_name='cultivos',
            name='ph',
        ),
        migrations.DeleteModel(
            name='Ph_Suelo',
        ),
    ]
