# Generated by Django 4.2.11 on 2026-03-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0051_remove_cultivos_distancia_remove_cultivos_ph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivos',
            name='familia',
            field=models.CharField(choices=[('COM', 'Compuestas'), ('CRU', 'Cruciferas (Brásicas)'), ('UMB', 'Cruciferas'), ('SOL', 'Solanaceas'), ('GRA', 'Gramineas'), ('LEG', 'Leguminosas'), ('QUE', 'Quenopoidaceas'), ('ALL', 'Alliaceas'), ('CUC', 'Cucurbitaceas'), ('CON', 'Convolvulaceas'), ('ASP', 'Asparagaceae'), ('API', 'Apiaceae')], max_length=3),
        ),
    ]
