# Generated by Django 3.2.13 on 2022-08-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0017_auto_20220812_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivos',
            name='tipo_siembra',
            field=models.CharField(choices=[('D', 'Directa'), ('S', 'Semillero'), ('T', 'Directa / Semillero')], max_length=1),
        ),
    ]
