# Generated by Django 3.2.13 on 2022-08-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0018_alter_cultivos_tipo_siembra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteros',
            name='ancho',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='canteros',
            name='largo',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='canteros',
            name='ubicacion_x',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='canteros',
            name='ubicacion_y',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='cultivos',
            name='distancia',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='huerta',
            name='ancho',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='huerta',
            name='largo',
            field=models.FloatField(blank=True),
        ),
    ]
