# Generated by Django 3.2.13 on 2023-03-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0020_cantero_cultivos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cultivos',
            old_name='especie',
            new_name='variedad',
        ),
        migrations.AddField(
            model_name='cultivos',
            name='familia',
            field=models.CharField(choices=[('COM', 'Compuestas'), ('CRU', 'Cruciferas (Brásicas)'), ('UMB', 'Cruciferas'), ('SOL', 'Solanaceas'), ('GRA', 'Gramineas'), ('LEG', 'Leguminosas'), ('QUE', 'Quenopoidaceas'), ('ALL', 'Alliaceas'), ('CUC', 'Cucurbitaceas')], default=' ', max_length=3),
            preserve_default=False,
        ),
    ]
