# Generated by Django 3.2.13 on 2023-03-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0022_tierras_cultivo_desc_corta'),
    ]

    operations = [
        migrations.AddField(
            model_name='plagas',
            name='agente_causal',
            field=models.CharField(choices=[('HON', 'Hongos'), ('BAC', 'Bacterias'), ('NEM', 'Nematodos'), ('VIR', 'Virus'), ('PAR', 'Plantas Parasitas')], default=' ', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plagas',
            name='sintomas',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
