# Generated by Django 3.2.13 on 2023-04-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0031_auto_20230410_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivos',
            name='distancia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cultivos',
            name='familia',
            field=models.CharField(choices=[('COM', 'Compuestas'), ('CRU', 'Cruciferas (Brásicas)'), ('UMB', 'Cruciferas'), ('SOL', 'Solanaceas'), ('GRA', 'Gramineas'), ('LEG', 'Leguminosas'), ('QUE', 'Quenopoidaceas'), ('ALL', 'Alliaceas'), ('CUC', 'Cucurbitaceas'), ('CON', 'Convolvulaceas')], max_length=3),
        ),
        migrations.AlterField(
            model_name='cultivos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cultivos'),
        ),
        migrations.AlterField(
            model_name='cultivos',
            name='luna_siembra',
            field=models.CharField(blank=True, choices=[('C', 'Cuarto Creciente'), ('M', 'Cuarto Menguante'), ('L', 'Llena'), ('N', 'Nueva')], max_length=1, null=True),
        ),
    ]
