# Generated by Django 3.2.13 on 2023-04-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0034_auto_20230413_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivos',
            name='fecha_siembra_desde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cultivos',
            name='fecha_siembra_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cultivos',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='cultivos'),
        ),
    ]
