# Generated by Django 4.2.11 on 2025-01-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopromesa',
            name='user',
        ),
        migrations.AddField(
            model_name='usuariopromesa',
            name='aleatorio',
            field=models.CharField(default="", max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariopromesa',
            name='email',
            field=models.EmailField(default="", max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariopromesa',
            name='fecha',
            field=models.DateTimeField(default="0001-01-01 01:01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariopromesa',
            name='first_name',
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariopromesa',
            name='last_name',
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariopromesa',
            name='username',
            field=models.CharField(default="", max_length=80, unique=True),
            preserve_default=False,
        ),
    ]
