# Generated by Django 4.2.11 on 2025-01-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_usuariopromesa_user_usuariopromesa_aleatorio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopromesa',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
