# Generated by Django 4.2.11 on 2025-04-03 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250, null=True, unique=True)),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('tipo', models.CharField(choices=[('P', 'Padre'), ('I', 'Intermedio'), ('H', 'Hoja')], max_length=1)),
                ('menuPadre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subMenu', to='accesibilidad.menu')),
            ],
        ),
        migrations.CreateModel(
            name='MenuGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accesibilidad.menu')),
            ],
        ),
    ]
