# Generated by Django 4.2.11 on 2025-04-07 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0040_remove_canteros_huerta_remove_huerta_hortelano_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('coord_x', models.FloatField(blank=True)),
                ('coord_y', models.FloatField(blank=True)),
                ('ancho', models.FloatField(blank=True)),
                ('largo', models.FloatField(blank=True)),
                ('hortelano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.hortelano')),
            ],
        ),
        migrations.CreateModel(
            name='Canteros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('ancho', models.FloatField(blank=True)),
                ('largo', models.FloatField(blank=True)),
                ('ubicacion_x', models.FloatField(blank=True)),
                ('ubicacion_y', models.FloatField(blank=True)),
                ('huerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huertas.huerta')),
            ],
        ),
        migrations.CreateModel(
            name='Cantero_Cultivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaSiembra', models.DateField(blank=True, null=True)),
                ('fechaCosecha', models.DateField(blank=True, null=True)),
                ('cantidad_sembrada', models.SmallIntegerField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('cantero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huertas.canteros')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.cultivos')),
            ],
        ),
    ]
